# debanding
D cycle deband

# shaders
g cycle-values glsl-shaders "~~/shaders/nnedi3-nns128-win8x4.hook" "~~/shaders/ArtCNN_C4F32.glsl" ""

# audio
z cycle audio
Z cycle audio down

# subtitles
x add sub-delay +0.1
X add sub-delay -0.1

Alt+x add secondary-sub-delay +0.1
Alt+X add secondary-sub-delay -0.1

c cycle sub
C cycle sub down
Alt+c cycle secondary-sid
Alt+C cycle secondary-sid down


K cycle_values sub-ass-override "force" "no"
